### ISSUE TITLE
Implement Unified Logging Framework for Uvicorn-Based Agents

### ISSUE THREAD

**Issue by lukehinds** [RedDotRocket/AgentUp#17]
**Description:**
Our current FastAPI/Uvicorn setup relies on the default Uvicorn logging configuration, which leads to inconsistencies in format, level naming, and output destinations across services. We need a pluggable, descriptor-driven logging framework that:

* Provides **structured, uniform logs** (e.g. JSON) for easy ingestion by log aggregators
* Allows per-agent configuration of levels, formats, and handlers (console, file, external)
* Integrates seamlessly with Uvicorn’s startup, request lifespan events, and exception handlers
* Supports contextual fields (agent name, request ID, trace ID, memory snapshots) automatically

All configuration should live in our agent descriptor so that teams can tweak logging without touching code.

---

**Acceptance Criteria:**

* [ ] **Descriptor Schema:** Extend agent descriptor with a `logging:` section, e.g.

  ```yaml
  logging:
    version: 1
    format: "json"           # or "text"
    level: "INFO"
    handlers:
      console:
        enabled: true
        format: "json"
      file:
        enabled: true
        path: "/var/log/agent.log"
        rotation: "daily"
      external:
        enabled: false
        url: "https://log-collector.example.com/ingest"
        api_key: "${{ LOG_API_KEY }}"
  ```
* [ ] **Initialization:** At app startup (before Uvicorn’s logger is configured), read the `logging:` config and:

  * Configure the root logger with the specified handlers and formats
  * Override Uvicorn’s default access and error loggers to use our handlers
* [ ] **Structured Context Injection:** All log calls (including FastAPI access logs) automatically include:

  * `agent_name` (from descriptor)
  * `request_id` and `trace_id` (generate or propagate via headers)
  * Timestamps in ISO 8601 UTC
* [ ] **Consistency Across Components:**

  * Ensure any third-party libraries that log (e.g. SQLAlchemy, HTTP clients) inherit our root logger configuration
  * Provide a helper decorator or middleware to capture unhandled exceptions and log them with stack traces and context
* [ ] **Configuration Overrides:**

  * Support environment-variable overrides for level and handlers per 12-factor best practices
* [ ] **Tests & Docs:**

  * Unit tests for parsing the `logging:` schema and applying handlers
  * Integration test spinning up Uvicorn with our config and asserting output format/fields
  * Documentation in `/docs/logging.md` with examples, best practices, and troubleshooting

---

**Tasks:**

* [ ] Define and validate the `logging:` section in the agent descriptor schema
* [ ] Build a logging‐configuration module that applies Python `logging.config.dictConfig` at startup
* [ ] Hook into Uvicorn’s logger names (`"uvicorn"`, `"uvicorn.error"`, `"uvicorn.access"`) to replace formatters/handlers
* [ ] Implement middleware or event‐handlers for request ID and trace ID propagation
* [ ] Write unit and integration tests covering default and custom configurations
* [ ] Update documentation with usage examples and recommended log aggregator setups

---

**References:**

* Uvicorn Logging Configuration: [https://www.uvicorn.org/#logging](https://www.uvicorn.org/#logging)
* Python `logging.config.dictConfig` Guide: [https://docs.python.org/3/library/logging.config.html#logging-config-dictschema](https://docs.python.org/3/library/logging.config.html#logging-config-dictschema)
